# Generated by Django 4.0.5 on 2022-06-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('tmodel', models.CharField(max_length=200)),
                ('fyear', models.IntegerField(default=1769)),
                ('color', models.CharField(max_length=100)),
                ('trucklicensenumber', models.CharField(max_length=50)),
                ('milesodometer', models.IntegerField(default=0)),
                ('milesformaintenance', models.IntegerField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('licensenumber', models.IntegerField(default=0)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='truckregister.truck')),
            ],
        ),
    ]
