# Generated by Django 4.0.5 on 2022-06-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckregister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='licensenumber',
            new_name='license_number',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='milesformaintenance',
            new_name='miles_for_maintenance',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='tmodel',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='milesodometer',
            new_name='odometer',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='trucklicensenumber',
            new_name='truck_license_number',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='fyear',
            new_name='year',
        ),
    ]
