# Generated by Django 4.0.5 on 2022-06-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckregister', '0002_rename_licensenumber_driver_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='brand',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='truck',
            name='color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='truck',
            name='miles_for_maintenance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='truck',
            name='odometer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_license_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.IntegerField(),
        ),
    ]
