# Generated by Django 4.0.5 on 2022-06-25 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckregister', '0003_alter_truck_brand_alter_truck_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='truckregister.truck'),
        ),
    ]
