# Generated by Django 4.0.5 on 2022-06-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckregister', '0004_driver_last_name_alter_driver_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
